name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo in the console output
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience to skip caching NuGet packages and speed up the build
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry to Microsoft

jobs:
  restore-build-test-pack:
    runs-on: ubuntu-latest
    steps:
    -
      name: Prepare - Checkout Code
      uses: actions/checkout@v6
    -
      name: Prepare - Read Version
      uses: bfren/read-file@v2
      with:
        file: ./Version
      id: version
    -
      name: Prepare - Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x
    -
      name: A - Restore
      run: |
        dotnet restore ./Test.csproj
    -
      name: B - Build
      run: |
        dotnet build ./Test.csproj \
          --no-restore \
          --configuration Release
    -
      name: C - Test
      run: |
        dotnet test ./Test.csproj \
          --no-restore \
          --no-build \
          --configuration Release
    -
      if: success()
      name: D - Pack
      run: |
        dotnet pack ./Pack.csproj \
          --no-build \
          --configuration Release \
          /p:PackageOutputPath=./$HOME/pack \
          -p:PackageVersion=${{ steps.version.outputs.contents }}
    -
      name: E - Store
      uses: actions/upload-artifact@v6
      with:
        name: nupkgs
        path: ./pack
  publish:
    runs-on: ubuntu-latest
    needs: restore-build-test-pack
    if: success()
    steps:
    - name: Retrieve Packages Artifact
      uses: actions/download-artifact@v7
      with:
        name: nupkgs
        path: ./pack
    -
      if: success()
      name: E - Push
      run: |
        dotnet nuget push "./pack/*.nupkg" \
          --skip-duplicate \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json
        dotnet nuget push "./pack/*.nupkg" \
          --skip-duplicate \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --source https://nuget.pkg.github.com/bfren/index.json
  notify:
    runs-on: ubuntu-latest
    needs: [restore-build-test-pack, publish]
    steps:
    -
      if: success()
      name: Finish - Success
      uses: bfren/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Wrap (GitHub)
        SLACK_MESSAGE: Publish Succeeded
        SLACK_COLOR: good
        SLACK_ICON: https://bfren.dev/img/logo-square-500x500.jpg
    -
      if: failure()
      name: Finish - Failure
      uses: bfren/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Wrap (GitHub)
        SLACK_MESSAGE: Publish Failed
        SLACK_COLOR: danger
        SLACK_ICON: https://bfren.dev/img/logo-square-500x500.jpg
